<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.3</version>
    </parent>

    <groupId>pab.ta.handler.tbank</groupId>
    <artifactId>signal-tbank</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modules>
        <module>strategy</module>
        <module>signal</module>
        <module>common</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <revision>0.0.1-SNAPSHOT</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <piapi.version>1.43</piapi.version>
        <signal.boot.version>0.0.8-SNAPSHOT</signal.boot.version>
        <vavr.version>0.10.4</vavr.version>
        <ta4j.version>0.22.1</ta4j.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-parent</artifactId>
                <version>2023.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.ta4j</groupId>
                <artifactId>ta4j-core</artifactId>
                <version>${ta4j.version}</version>
            </dependency>
            <dependency>
                <groupId>pab.ta.handler.base.boot</groupId>
                <artifactId>signal-base-boot-starter</artifactId>
                <version>${signal.boot.version}</version>
            </dependency>
            <dependency>
                <groupId>ru.tinkoff.piapi</groupId>
                <artifactId>java-sdk-core</artifactId>
                <version>${piapi.version}</version>
            </dependency>
            <dependency>
                <groupId>ru.tinkoff.piapi</groupId>
                <artifactId>java-sdk-strategy</artifactId>
                <version>${piapi.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vavr</groupId>
                <artifactId>vavr</artifactId>
                <version>${vavr.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.7.3</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
