<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pab.ta.handler.tbank</groupId>
        <artifactId>signal-tbank</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>common</artifactId>

    <dependencies>
        <dependency>
            <groupId>pab.ta.handler.base.boot</groupId>
            <artifactId>signal-base-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ru.tinkoff.piapi</groupId>
            <artifactId>java-sdk-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.ta4j</groupId>
            <artifactId>ta4j-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ru.tinkoff.piapi</groupId>
            <artifactId>java-sdk-strategy</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.ta4j</groupId>
                    <artifactId>ta4j-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

</project>
